# Generated by Django 6.1 on 2026-08-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField()),
                ('tipo', models.CharField(choices=[('pelicula', 'Película'), ('serie', 'Serie')], max_length=10)),
                ('nombre', models.CharField(max_length=200)),
                ('sinopsis', models.TextField(blank=True)),
                ('poster', models.URLField(blank=True)),
                ('anio', models.CharField(blank=True, max_length=10)),
                ('voto_tmdb', models.FloatField(default=0)),
                ('generos', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('pendiente', 'Por ver'), ('viendo', 'Viendo'), ('vista', 'Vista')], default='pendiente', max_length=10)),
                ('mi_nota', models.IntegerField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True)),
                ('agregado_el', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-agregado_el'],
                'constraints': [models.UniqueConstraint(fields=('tmdb_id', 'tipo'), name='unico_tmdb_tipo')],
            },
        ),
    ]
