# Generated by Django 6.1 on 2026-08-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulo',
            name='duracion_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='titulo',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='titulo',
            name='fecha_vista',
            field=models.DateField(blank=True, null=True),
        ),
    ]
